version: "3.8"
services:
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=spring-days
      - RABBITMQ_DEFAULT_PASS=spring-days
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: spring-days
      POSTGRES_USER: spring-days
      POSTGRES_PASSWORD: spring-days
  redis:
    image: redis
    ports:
      - "6379"
  spring-days-api:
    image: spring-days
    container_name: spring-days
    build:
      context: .
    ports:
      - "8888:8080"
    environment:
      JAVA_OPTS: -DXmx1g
      SPRING_PROFILES_ACTIVE: local-standalone
    links:
      - postgres
      - rabbitmq3
      - redis
    depends_on:
      - postgres
      - rabbitmq3
      - redis