spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/spring-days
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root

  # Rabbitmq3 Config
  rabbitmq:
    port: 5672
    host:  rabbitmq3
    username: guest
    password: guest
    queue:
      name: spring-days

  # Redis Config
  redis:
    host: redis
    port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
      springframework:
        web:
          client:
            RestTemplate: DEBUG

management:
  endpoint:
    health:
      show-details: always

setting:
  service:
    internal:
      name: 'bfi-tms-backoffice'
      key: INTERNAL_KEY
  jwt:
    token:
      issuer: MY_LOCAL_MACHINE
    jks:
      filePath: './add-your-jks-here.jks'
      filePassword: 'P@ssw0rd'
      keyName: 'jwt_key'
      keyPassword: 'P@ssw0rd'