spring:
  profiles: h2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./h2/data/spring_db
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      pen-in-view: false
      generate-ddl: true
      database: h2s
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true

spring-doc:
  version: '3.0'
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

setting:
  service:
    internal:
      name: todo-replace-me
      key: 649085694586958
  jwt:
    token:
      issuer: LOCAL
    jks:
      filePath: './add-your-jks-here.jks'
      filePassword: 'P@ssw0rd'
      keyName: 'jwt_key'
      keyPassword: 'P@ssw0rd'
    secret: SECRET

