@startuml
actor Member
participant System
database user

Member -> System : login()
System -> user : findUsernameAndPassword()
user -> System : foundUser()
user -> Member : success()
System -> Member : end()

@enduml
